apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-test-model-server-241201-gitops
spec:  
  template:         
    metadata:
      name: dsp-clone-job-test-model-server-241201-gitops
    spec:  
      serviceAccountName: test-model-server-241201-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/utils:latest
        command:
        - /bin/bash
        - -c
        - |
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc wait -l statefulset=test-model-server-241201-notebook --for=condition=ready pod --timeout=300s
          oc exec  StatefulSet/test-model-server-241201-notebook -- git clone https://github.com/fpetk/test-model-server-241201
      restartPolicy: Never